name: Auto-generate Documentation

permissions:
  contents: write  # Allows pushing changes to the repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate documentation
      run: python linealert/generate_docs.py

    - name: Commit documentation updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add documentation_output.md || true
        git diff --cached --quiet || git commit -m "Auto-generate documentation"
        git push
