# name: Auto-generate Documentation
#
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#
#       - name: Run doc generation script
#         run: ./scripts/generate_docs.sh
