name: generate_docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate documentation
        run: python linealert/generate_docs.py

      # Optional: commit changes if documentation_output.md is updated
      # Uncomment below ONLY if you're using a proper GitHub token with write access

      # - name: Commit documentation updates
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add documentation_output.md
      #     git diff --cached --quiet || git commit -m "Auto-update documentation"
      #     git push
